/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuLieuRouteImport } from './routes/tu-lieu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as GhiChuRouteImport } from './routes/ghi-chu'
import { Route as DuAnRouteImport } from './routes/du-an'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as AmNhacRouteImport } from './routes/am-nhac'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DuAnIndexRouteImport } from './routes/du-an.index'
import { Route as DuAnSlugRouteImport } from './routes/du-an.$slug'

const TuLieuRoute = TuLieuRouteImport.update({
  id: '/tu-lieu',
  path: '/tu-lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const GhiChuRoute = GhiChuRouteImport.update({
  id: '/ghi-chu',
  path: '/ghi-chu',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnRoute = DuAnRouteImport.update({
  id: '/du-an',
  path: '/du-an',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const AmNhacRoute = AmNhacRouteImport.update({
  id: '/am-nhac',
  path: '/am-nhac',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnIndexRoute = DuAnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DuAnRoute,
} as any)
const DuAnSlugRoute = DuAnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DuAnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/am-nhac': typeof AmNhacRoute
  '/dang-nhap': typeof DangNhapRoute
  '/du-an': typeof DuAnRouteWithChildren
  '/ghi-chu': typeof GhiChuRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tu-lieu': typeof TuLieuRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/du-an/': typeof DuAnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/am-nhac': typeof AmNhacRoute
  '/dang-nhap': typeof DangNhapRoute
  '/ghi-chu': typeof GhiChuRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tu-lieu': typeof TuLieuRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/du-an': typeof DuAnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/am-nhac': typeof AmNhacRoute
  '/dang-nhap': typeof DangNhapRoute
  '/du-an': typeof DuAnRouteWithChildren
  '/ghi-chu': typeof GhiChuRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tu-lieu': typeof TuLieuRoute
  '/du-an/$slug': typeof DuAnSlugRoute
  '/du-an/': typeof DuAnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/am-nhac'
    | '/dang-nhap'
    | '/du-an'
    | '/ghi-chu'
    | '/gioi-thieu'
    | '/lien-he'
    | '/sitemap.xml'
    | '/tu-lieu'
    | '/du-an/$slug'
    | '/du-an/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/am-nhac'
    | '/dang-nhap'
    | '/ghi-chu'
    | '/gioi-thieu'
    | '/lien-he'
    | '/sitemap.xml'
    | '/tu-lieu'
    | '/du-an/$slug'
    | '/du-an'
  id:
    | '__root__'
    | '/'
    | '/am-nhac'
    | '/dang-nhap'
    | '/du-an'
    | '/ghi-chu'
    | '/gioi-thieu'
    | '/lien-he'
    | '/sitemap.xml'
    | '/tu-lieu'
    | '/du-an/$slug'
    | '/du-an/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmNhacRoute: typeof AmNhacRoute
  DangNhapRoute: typeof DangNhapRoute
  DuAnRoute: typeof DuAnRouteWithChildren
  GhiChuRoute: typeof GhiChuRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TuLieuRoute: typeof TuLieuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tu-lieu': {
      id: '/tu-lieu'
      path: '/tu-lieu'
      fullPath: '/tu-lieu'
      preLoaderRoute: typeof TuLieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghi-chu': {
      id: '/ghi-chu'
      path: '/ghi-chu'
      fullPath: '/ghi-chu'
      preLoaderRoute: typeof GhiChuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an': {
      id: '/du-an'
      path: '/du-an'
      fullPath: '/du-an'
      preLoaderRoute: typeof DuAnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/am-nhac': {
      id: '/am-nhac'
      path: '/am-nhac'
      fullPath: '/am-nhac'
      preLoaderRoute: typeof AmNhacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/': {
      id: '/du-an/'
      path: '/'
      fullPath: '/du-an/'
      preLoaderRoute: typeof DuAnIndexRouteImport
      parentRoute: typeof DuAnRoute
    }
    '/du-an/$slug': {
      id: '/du-an/$slug'
      path: '/$slug'
      fullPath: '/du-an/$slug'
      preLoaderRoute: typeof DuAnSlugRouteImport
      parentRoute: typeof DuAnRoute
    }
  }
}

interface DuAnRouteChildren {
  DuAnSlugRoute: typeof DuAnSlugRoute
  DuAnIndexRoute: typeof DuAnIndexRoute
}

const DuAnRouteChildren: DuAnRouteChildren = {
  DuAnSlugRoute: DuAnSlugRoute,
  DuAnIndexRoute: DuAnIndexRoute,
}

const DuAnRouteWithChildren = DuAnRoute._addFileChildren(DuAnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmNhacRoute: AmNhacRoute,
  DangNhapRoute: DangNhapRoute,
  DuAnRoute: DuAnRouteWithChildren,
  GhiChuRoute: GhiChuRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TuLieuRoute: TuLieuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
